name: "Generator"
on:
  workflow_dispatch:
  push:

jobs:
  Generator:
    permissions: write-all # required by push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version tag
        run: |
          bash ./wechat-linux-version.sh
          # commit
          if [[ $(git diff --stat) != '' ]]; then
            git config user.signingkey "github-actions[bot]@users.noreply.github.com"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
          	git add .
          	git commit -m "$(TZ=Asia/Shanghai date +%Y-%m-%dT%H:%M:%S%z) update"
          	git push
          fi

